package configutil

import (
	"github.com/devspace-cloud/devspace/pkg/devspace/config/versions/latest"
	"github.com/devspace-cloud/devspace/pkg/util/ptr"
)

// TestNamespace is the test namespace to use
const TestNamespace = "test-namespace"

// SetFakeConfig initializes the config objects
func SetFakeConfig(fakeConfig *latest.Config) {
	getConfigOnce.Do(func() {})

	if fakeConfig.Deployments == nil {
		fakeConfig.Deployments = &[]*latest.DeploymentConfig{}
	}
	if fakeConfig.Images == nil {
		fakeConfig.Images = &map[string]*latest.ImageConfig{}
	}
	if fakeConfig.Dev == nil {
		fakeConfig.Dev = &latest.DevConfig{}
	}

	fakeConfig.Cluster = &latest.Cluster{
		APIServer: ptr.String("https://127.0.0.1"),
		Namespace: ptr.String(TestNamespace),
		// Test ca cert
		CaCert: ptr.String("LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRFNE1USXhNekUwTVRrd05sb1hEVEk0TVRJeE1URTBNVGt3Tmxvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTHNPCnlhcklRVWwrZW5xZWFJanlrK1BXckF6MnhqbTRWM0Y3eVdNaVhUVFIvRG03ekNiNmczc08xVFp4M00zMnAvaVQKc0xTWjVoL3Y5bXEvQy80blgvQUo0dkt0T3NVMkxZM2xjcG43ei94ZDkzL1NOMWlxMkt3WFF3cjJGVXZQZnExSQpoNW5nUnF0TjIvWHozQnYwdURWMUpzMUZ5dlVuRGdMaThDdW0rTFJ3RXF0U3Y5WEt5bk4rRnk0ckxGckRSUFk3CjE2bW1TZWxIZFJzL2huQnBTOGZ3bFQ4Qk1GUmdtTk56bW1ROFBmRjFUMkdhSzFPSW5vQThBeWRHUlVJZVlnOEYKd091aU92YWJaNVlZUk9mMjdzU2pFTWg2NklMSXlJOHVUdmJvb3ZQNWV5dTVCZzIrdTdpSktkbXYzc3FtY1hwbwpBVUF1akU1Nkc3WU5tU2FPMG84Q0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFDQkxRQnhtc1luWWFzUnFpYUMyVTFhOHEybWMrWUZiZERiR0IyMHQ0SGVnRWozKzJzegprTmFzWTZhWm5JN25sc3lXbm1xOTRvZzljMEF5ci9UM0V5NTRFZzhuTU5qeUtkZ0Fnd3p1YjRGbm85dEpnVkovCndReUJHUkZqTTJncUdtZ2FQb2FQQmJNelFlSzNCR1J0bXJyVDBWWVdveTFPMHhuWnJlQUJYT3pJMU55YnpZalIKSGhvVlpZalh0TUF2M3o2WXU5U2YxWko3WHpMdmt3WnI3Mmh6WUhaNk0vcG5JYmZvTU91WEEyNWVobktndjFETQoyTnpBV0UvYVBNUXZsSzNiVkZRdjhZeUtTbWFXWXhDTGJISjFQZ204QkdIUXJJRlBMV0FvL21tZjBSUWFwQzFnCmRzVEpVUG9jL21OU0tTejhEczZYaVRlYy81ZmwwaUhlVGQrbQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="),
		User: &latest.ClusterUser{
			// Test token
			Token: ptr.String("eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImRlZmF1bHQtdG9rZW4tcHN0bnMiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZGVmYXVsdCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjUwZWNjYzg1LTZiNmUtMTFlOS04MzQzLTZhNmRmZmFmOTdkMiIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OmRlZmF1bHQifQ.qSyDOWS1J2TNbIa0AOACTWRQPnnHDR9sDg5O_P5HX1XpfdT30BSOD34g4MLZipk2AIBMPABLfrjyv93dFzcmpvmcXT9sORzFSzB1oLkT8-U346gnJb-0V7YOivH_f3wye2kkPX_L4-OzAhgwFGDNY6mvFOYU7XWIDBpYabMy2HPHCdIJy9u8V96owOmr9sfPbxVu9Y85D2jq15mdElUZ6ttw5N_KtGO-0C2PaT4JmfYetLn9dSKjvFfWUfQwNryOpAD4MdCQfAVjKi7fi4DkwCHo7rraHrqJAmaQvGqHFdDl77AKDAT4UG70H1WimE3jOO6m0sKCM9vlVP2M1BlbZg"),
		},
	}

	config = fakeConfig
}
