
<details className="config-field" data-expandable="false" open>
<summary>

### `dockerfile` <span className="config-field-required" data-required="false">required</span> <span className="config-field-type">string</span> <span className="config-field-default">./Dockerfile</span> <span className="config-field-enum"></span> {#images-dockerfile}

Dockerfile specifies a path (relative or absolute) to the dockerfile. Defaults to ./Dockerfile.

</summary>



</details>
