
<details className="config-field" data-expandable="false" open>
<summary>

### `dockerfile` <span class="config-field-required" data-required="false">required</span> <span class="config-field-type">string</span> <span class="config-field-default">./Dockerfile</span> <span class="config-field-enum"></span>

Dockerfile specifies a path (relative or absolute) to the dockerfile. Defaults
to ./Dockerfile

</summary>



</details>
