
<details>
<summary>

`dockerfile`  <span class="config-field-type">string</span> 

</summary>

Dockerfile specifies a path (relative or absolute) to the dockerfile. Defaults
to ./Dockerfile

</details>
