name: Bug Report
description: Report a bug encountered while operating devspace
labels:
- kind/bug
body:
  - type: textarea
    id: problem
    attributes:
      label: What happened?
      description: |
        Please provide as much info as possible.
        Not doing so may result in your bug not being addressed in a timely manner.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: How can we reproduce it (as minimally and precisely as possible)?
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Anything else we need to know?

  - type: textarea
    id: devspaceYaml
    attributes:
      label: devspace.yaml
      value: |
        <details>

        ```
        # paste devspace.yaml here
        ```

        </details>
    validations:
      required: true

  - type: textarea
    id: devspaceVersion
    attributes:
      label: DevSpace version
      value: |
        <details>

        ```console
        $ devspace --version
        # paste output here
        ```

        </details>
    validations:
      required: true

  - type: textarea
    id: osVersion
    attributes:
      label: OS and Arch
      value: |
        <details>

        ```
        OS:
        Arch:
        ```
        </details>
    validations:
      required: true

  - type: textarea
    id: k8sVersion
    attributes:
      label: Kubernetes cluster version
      value: |
        <details>

        ```console
        $ kubectl version
        # paste output here
        ```

        </details>
    validations:
      required: true

  - type: textarea
    id: cloudProvider
    attributes:
      label: Cloud Provider e.g gcp | aws | azure
      value: |
        <details>

        ```console
        ```

        </details>
