apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: devspace-app
  name: external
spec:
  ports:
  - name: port-0
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/component: {{ $.Release.Name | quote }}
    app.kubernetes.io/name: devspace-app
  type: ClusterIP
