// Code generated by protoc-gen-go. DO NOT EDIT.
// source: remote.proto

package remote

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ChangeType int32

const (
	ChangeType_CHANGE ChangeType = 0
	ChangeType_DELETE ChangeType = 1
)

var ChangeType_name = map[int32]string{
	0: "CHANGE",
	1: "DELETE",
}

var ChangeType_value = map[string]int32{
	"CHANGE": 0,
	"DELETE": 1,
}

func (x ChangeType) String() string {
	return proto.EnumName(ChangeType_name, int32(x))
}

func (ChangeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_eefc82927d57d89b, []int{0}
}

type Watch struct {
	Path                 string   `protobuf:"bytes,1,opt,name=Path,proto3" json:"Path,omitempty"`
	Exclude              []string `protobuf:"bytes,2,rep,name=Exclude,proto3" json:"Exclude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Watch) Reset()         { *m = Watch{} }
func (m *Watch) String() string { return proto.CompactTextString(m) }
func (*Watch) ProtoMessage()    {}
func (*Watch) Descriptor() ([]byte, []int) {
	return fileDescriptor_eefc82927d57d89b, []int{0}
}

func (m *Watch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Watch.Unmarshal(m, b)
}
func (m *Watch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Watch.Marshal(b, m, deterministic)
}
func (m *Watch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Watch.Merge(m, src)
}
func (m *Watch) XXX_Size() int {
	return xxx_messageInfo_Watch.Size(m)
}
func (m *Watch) XXX_DiscardUnknown() {
	xxx_messageInfo_Watch.DiscardUnknown(m)
}

var xxx_messageInfo_Watch proto.InternalMessageInfo

func (m *Watch) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Watch) GetExclude() []string {
	if m != nil {
		return m.Exclude
	}
	return nil
}

type Change struct {
	ChangeType           ChangeType `protobuf:"varint,1,opt,name=ChangeType,proto3,enum=remote.ChangeType" json:"ChangeType,omitempty"`
	Path                 string     `protobuf:"bytes,2,opt,name=Path,proto3" json:"Path,omitempty"`
	Mtime                int64      `protobuf:"varint,3,opt,name=Mtime,proto3" json:"Mtime,omitempty"`
	Size                 int64      `protobuf:"varint,4,opt,name=Size,proto3" json:"Size,omitempty"`
	IsDir                bool       `protobuf:"varint,5,opt,name=IsDir,proto3" json:"IsDir,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Change) Reset()         { *m = Change{} }
func (m *Change) String() string { return proto.CompactTextString(m) }
func (*Change) ProtoMessage()    {}
func (*Change) Descriptor() ([]byte, []int) {
	return fileDescriptor_eefc82927d57d89b, []int{1}
}

func (m *Change) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Change.Unmarshal(m, b)
}
func (m *Change) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Change.Marshal(b, m, deterministic)
}
func (m *Change) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Change.Merge(m, src)
}
func (m *Change) XXX_Size() int {
	return xxx_messageInfo_Change.Size(m)
}
func (m *Change) XXX_DiscardUnknown() {
	xxx_messageInfo_Change.DiscardUnknown(m)
}

var xxx_messageInfo_Change proto.InternalMessageInfo

func (m *Change) GetChangeType() ChangeType {
	if m != nil {
		return m.ChangeType
	}
	return ChangeType_CHANGE
}

func (m *Change) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Change) GetMtime() int64 {
	if m != nil {
		return m.Mtime
	}
	return 0
}

func (m *Change) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Change) GetIsDir() bool {
	if m != nil {
		return m.IsDir
	}
	return false
}

type Excluded struct {
	Paths                []string `protobuf:"bytes,1,rep,name=Paths,proto3" json:"Paths,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Excluded) Reset()         { *m = Excluded{} }
func (m *Excluded) String() string { return proto.CompactTextString(m) }
func (*Excluded) ProtoMessage()    {}
func (*Excluded) Descriptor() ([]byte, []int) {
	return fileDescriptor_eefc82927d57d89b, []int{2}
}

func (m *Excluded) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Excluded.Unmarshal(m, b)
}
func (m *Excluded) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Excluded.Marshal(b, m, deterministic)
}
func (m *Excluded) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Excluded.Merge(m, src)
}
func (m *Excluded) XXX_Size() int {
	return xxx_messageInfo_Excluded.Size(m)
}
func (m *Excluded) XXX_DiscardUnknown() {
	xxx_messageInfo_Excluded.DiscardUnknown(m)
}

var xxx_messageInfo_Excluded proto.InternalMessageInfo

func (m *Excluded) GetPaths() []string {
	if m != nil {
		return m.Paths
	}
	return nil
}

type Path struct {
	Path                 string   `protobuf:"bytes,1,opt,name=Path,proto3" json:"Path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Path) Reset()         { *m = Path{} }
func (m *Path) String() string { return proto.CompactTextString(m) }
func (*Path) ProtoMessage()    {}
func (*Path) Descriptor() ([]byte, []int) {
	return fileDescriptor_eefc82927d57d89b, []int{3}
}

func (m *Path) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Path.Unmarshal(m, b)
}
func (m *Path) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Path.Marshal(b, m, deterministic)
}
func (m *Path) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Path.Merge(m, src)
}
func (m *Path) XXX_Size() int {
	return xxx_messageInfo_Path.Size(m)
}
func (m *Path) XXX_DiscardUnknown() {
	xxx_messageInfo_Path.DiscardUnknown(m)
}

var xxx_messageInfo_Path proto.InternalMessageInfo

func (m *Path) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type Chunk struct {
	Content              []byte   `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chunk) Reset()         { *m = Chunk{} }
func (m *Chunk) String() string { return proto.CompactTextString(m) }
func (*Chunk) ProtoMessage()    {}
func (*Chunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_eefc82927d57d89b, []int{4}
}

func (m *Chunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chunk.Unmarshal(m, b)
}
func (m *Chunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chunk.Marshal(b, m, deterministic)
}
func (m *Chunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chunk.Merge(m, src)
}
func (m *Chunk) XXX_Size() int {
	return xxx_messageInfo_Chunk.Size(m)
}
func (m *Chunk) XXX_DiscardUnknown() {
	xxx_messageInfo_Chunk.DiscardUnknown(m)
}

var xxx_messageInfo_Chunk proto.InternalMessageInfo

func (m *Chunk) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_eefc82927d57d89b, []int{5}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("remote.ChangeType", ChangeType_name, ChangeType_value)
	proto.RegisterType((*Watch)(nil), "remote.Watch")
	proto.RegisterType((*Change)(nil), "remote.Change")
	proto.RegisterType((*Excluded)(nil), "remote.Excluded")
	proto.RegisterType((*Path)(nil), "remote.Path")
	proto.RegisterType((*Chunk)(nil), "remote.Chunk")
	proto.RegisterType((*Empty)(nil), "remote.Empty")
}

func init() { proto.RegisterFile("remote.proto", fileDescriptor_eefc82927d57d89b) }

var fileDescriptor_eefc82927d57d89b = []byte{
	// 356 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x5d, 0x4b, 0xc3, 0x30,
	0x14, 0x5d, 0xb6, 0xb5, 0xeb, 0x2e, 0x73, 0x8c, 0xe0, 0x43, 0xd8, 0x53, 0x0d, 0x3e, 0xd4, 0x29,
	0x53, 0x2a, 0xfe, 0x00, 0xe9, 0x8a, 0x0a, 0x2a, 0x12, 0x37, 0x7c, 0xae, 0x5b, 0xb0, 0xc3, 0xb5,
	0x29, 0x6d, 0xa6, 0xce, 0x5f, 0xe1, 0xa3, 0x3f, 0x57, 0x92, 0xb4, 0xfb, 0x80, 0x81, 0x6f, 0xf7,
	0xf4, 0x9e, 0x7b, 0xcf, 0x39, 0xb7, 0x81, 0x4e, 0xce, 0x13, 0x21, 0xf9, 0x30, 0xcb, 0x85, 0x14,
	0xd8, 0x36, 0x88, 0x5e, 0x81, 0xf5, 0x12, 0xc9, 0x69, 0x8c, 0x31, 0x34, 0x9f, 0x22, 0x19, 0x13,
	0xe4, 0x22, 0xaf, 0xcd, 0x74, 0x8d, 0x09, 0xb4, 0xc2, 0xaf, 0xe9, 0x62, 0x39, 0xe3, 0xa4, 0xee,
	0x36, 0xbc, 0x36, 0xab, 0x20, 0xfd, 0x41, 0x60, 0x07, 0x71, 0x94, 0xbe, 0x71, 0xec, 0x03, 0x98,
	0x6a, 0xbc, 0xca, 0xb8, 0x1e, 0xef, 0xfa, 0x78, 0x58, 0x8a, 0x6d, 0x3a, 0x6c, 0x8b, 0xb5, 0x16,
	0xab, 0x6f, 0x89, 0x1d, 0x82, 0xf5, 0x20, 0xe7, 0x09, 0x27, 0x0d, 0x17, 0x79, 0x0d, 0x66, 0x80,
	0x62, 0x3e, 0xcf, 0xbf, 0x39, 0x69, 0xea, 0x8f, 0xba, 0x56, 0xcc, 0xbb, 0x62, 0x34, 0xcf, 0x89,
	0xe5, 0x22, 0xcf, 0x61, 0x06, 0x50, 0x17, 0x9c, 0xd2, 0xdd, 0x4c, 0x31, 0xd4, 0xce, 0x82, 0x20,
	0x6d, 0xdb, 0x00, 0xda, 0x37, 0xaa, 0xfb, 0xa2, 0xd2, 0x23, 0xb0, 0x82, 0x78, 0x99, 0xbe, 0xab,
	0xcc, 0x81, 0x48, 0x25, 0x4f, 0xa5, 0xee, 0x77, 0x58, 0x05, 0x69, 0x0b, 0xac, 0x30, 0xc9, 0xe4,
	0x6a, 0x70, 0xbc, 0x9d, 0x18, 0x03, 0xd8, 0xc1, 0xed, 0xf5, 0xe3, 0x4d, 0xd8, 0xab, 0xa9, 0x7a,
	0x14, 0xde, 0x87, 0xe3, 0xb0, 0x87, 0xfc, 0x5f, 0x04, 0x30, 0x12, 0x9f, 0x69, 0x21, 0x73, 0x1e,
	0x25, 0xf8, 0x14, 0x9c, 0x40, 0x24, 0x59, 0xce, 0x8b, 0x02, 0x77, 0xaa, 0xf3, 0x28, 0xe9, 0xfe,
	0x41, 0x85, 0xf4, 0x76, 0x5a, 0xf3, 0x10, 0x3e, 0x03, 0x47, 0x8d, 0x2e, 0x44, 0x34, 0xc3, 0xbb,
	0xed, 0x0d, 0x5b, 0xdb, 0xa5, 0xb5, 0x0b, 0x84, 0xcf, 0xa1, 0x65, 0xfc, 0x14, 0xb8, 0xb7, 0x26,
	0x97, 0xa7, 0xe8, 0x77, 0x77, 0x7f, 0x85, 0x1a, 0xf0, 0x23, 0x70, 0x26, 0x59, 0xe9, 0x6b, 0x00,
	0xf6, 0x24, 0xdb, 0x15, 0xd2, 0x9b, 0xf7, 0xd9, 0x3a, 0x01, 0x9b, 0xf1, 0x44, 0x7c, 0xf0, 0x7f,
	0x13, 0xbc, 0xda, 0xfa, 0x99, 0x5d, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff, 0x45, 0xa4, 0x3f, 0x62,
	0x76, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DownstreamClient is the client API for Downstream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DownstreamClient interface {
	Compress(ctx context.Context, opts ...grpc.CallOption) (Downstream_CompressClient, error)
	Download(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Downstream_DownloadClient, error)
	Changes(ctx context.Context, in *Excluded, opts ...grpc.CallOption) (Downstream_ChangesClient, error)
}

type downstreamClient struct {
	cc *grpc.ClientConn
}

func NewDownstreamClient(cc *grpc.ClientConn) DownstreamClient {
	return &downstreamClient{cc}
}

func (c *downstreamClient) Compress(ctx context.Context, opts ...grpc.CallOption) (Downstream_CompressClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Downstream_serviceDesc.Streams[0], "/remote.Downstream/Compress", opts...)
	if err != nil {
		return nil, err
	}
	x := &downstreamCompressClient{stream}
	return x, nil
}

type Downstream_CompressClient interface {
	Send(*Path) error
	CloseAndRecv() (*Empty, error)
	grpc.ClientStream
}

type downstreamCompressClient struct {
	grpc.ClientStream
}

func (x *downstreamCompressClient) Send(m *Path) error {
	return x.ClientStream.SendMsg(m)
}

func (x *downstreamCompressClient) CloseAndRecv() (*Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *downstreamClient) Download(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Downstream_DownloadClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Downstream_serviceDesc.Streams[1], "/remote.Downstream/Download", opts...)
	if err != nil {
		return nil, err
	}
	x := &downstreamDownloadClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Downstream_DownloadClient interface {
	Recv() (*Chunk, error)
	grpc.ClientStream
}

type downstreamDownloadClient struct {
	grpc.ClientStream
}

func (x *downstreamDownloadClient) Recv() (*Chunk, error) {
	m := new(Chunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *downstreamClient) Changes(ctx context.Context, in *Excluded, opts ...grpc.CallOption) (Downstream_ChangesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Downstream_serviceDesc.Streams[2], "/remote.Downstream/Changes", opts...)
	if err != nil {
		return nil, err
	}
	x := &downstreamChangesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Downstream_ChangesClient interface {
	Recv() (*Change, error)
	grpc.ClientStream
}

type downstreamChangesClient struct {
	grpc.ClientStream
}

func (x *downstreamChangesClient) Recv() (*Change, error) {
	m := new(Change)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DownstreamServer is the server API for Downstream service.
type DownstreamServer interface {
	Compress(Downstream_CompressServer) error
	Download(*Empty, Downstream_DownloadServer) error
	Changes(*Excluded, Downstream_ChangesServer) error
}

func RegisterDownstreamServer(s *grpc.Server, srv DownstreamServer) {
	s.RegisterService(&_Downstream_serviceDesc, srv)
}

func _Downstream_Compress_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DownstreamServer).Compress(&downstreamCompressServer{stream})
}

type Downstream_CompressServer interface {
	SendAndClose(*Empty) error
	Recv() (*Path, error)
	grpc.ServerStream
}

type downstreamCompressServer struct {
	grpc.ServerStream
}

func (x *downstreamCompressServer) SendAndClose(m *Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *downstreamCompressServer) Recv() (*Path, error) {
	m := new(Path)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Downstream_Download_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DownstreamServer).Download(m, &downstreamDownloadServer{stream})
}

type Downstream_DownloadServer interface {
	Send(*Chunk) error
	grpc.ServerStream
}

type downstreamDownloadServer struct {
	grpc.ServerStream
}

func (x *downstreamDownloadServer) Send(m *Chunk) error {
	return x.ServerStream.SendMsg(m)
}

func _Downstream_Changes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Excluded)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DownstreamServer).Changes(m, &downstreamChangesServer{stream})
}

type Downstream_ChangesServer interface {
	Send(*Change) error
	grpc.ServerStream
}

type downstreamChangesServer struct {
	grpc.ServerStream
}

func (x *downstreamChangesServer) Send(m *Change) error {
	return x.ServerStream.SendMsg(m)
}

var _Downstream_serviceDesc = grpc.ServiceDesc{
	ServiceName: "remote.Downstream",
	HandlerType: (*DownstreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Compress",
			Handler:       _Downstream_Compress_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Download",
			Handler:       _Downstream_Download_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Changes",
			Handler:       _Downstream_Changes_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "remote.proto",
}

// UpstreamClient is the client API for Upstream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UpstreamClient interface {
	Upload(ctx context.Context, opts ...grpc.CallOption) (Upstream_UploadClient, error)
	Remove(ctx context.Context, opts ...grpc.CallOption) (Upstream_RemoveClient, error)
}

type upstreamClient struct {
	cc *grpc.ClientConn
}

func NewUpstreamClient(cc *grpc.ClientConn) UpstreamClient {
	return &upstreamClient{cc}
}

func (c *upstreamClient) Upload(ctx context.Context, opts ...grpc.CallOption) (Upstream_UploadClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Upstream_serviceDesc.Streams[0], "/remote.Upstream/Upload", opts...)
	if err != nil {
		return nil, err
	}
	x := &upstreamUploadClient{stream}
	return x, nil
}

type Upstream_UploadClient interface {
	Send(*Chunk) error
	CloseAndRecv() (*Empty, error)
	grpc.ClientStream
}

type upstreamUploadClient struct {
	grpc.ClientStream
}

func (x *upstreamUploadClient) Send(m *Chunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *upstreamUploadClient) CloseAndRecv() (*Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *upstreamClient) Remove(ctx context.Context, opts ...grpc.CallOption) (Upstream_RemoveClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Upstream_serviceDesc.Streams[1], "/remote.Upstream/Remove", opts...)
	if err != nil {
		return nil, err
	}
	x := &upstreamRemoveClient{stream}
	return x, nil
}

type Upstream_RemoveClient interface {
	Send(*Path) error
	CloseAndRecv() (*Empty, error)
	grpc.ClientStream
}

type upstreamRemoveClient struct {
	grpc.ClientStream
}

func (x *upstreamRemoveClient) Send(m *Path) error {
	return x.ClientStream.SendMsg(m)
}

func (x *upstreamRemoveClient) CloseAndRecv() (*Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// UpstreamServer is the server API for Upstream service.
type UpstreamServer interface {
	Upload(Upstream_UploadServer) error
	Remove(Upstream_RemoveServer) error
}

func RegisterUpstreamServer(s *grpc.Server, srv UpstreamServer) {
	s.RegisterService(&_Upstream_serviceDesc, srv)
}

func _Upstream_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(UpstreamServer).Upload(&upstreamUploadServer{stream})
}

type Upstream_UploadServer interface {
	SendAndClose(*Empty) error
	Recv() (*Chunk, error)
	grpc.ServerStream
}

type upstreamUploadServer struct {
	grpc.ServerStream
}

func (x *upstreamUploadServer) SendAndClose(m *Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *upstreamUploadServer) Recv() (*Chunk, error) {
	m := new(Chunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Upstream_Remove_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(UpstreamServer).Remove(&upstreamRemoveServer{stream})
}

type Upstream_RemoveServer interface {
	SendAndClose(*Empty) error
	Recv() (*Path, error)
	grpc.ServerStream
}

type upstreamRemoveServer struct {
	grpc.ServerStream
}

func (x *upstreamRemoveServer) SendAndClose(m *Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *upstreamRemoveServer) Recv() (*Path, error) {
	m := new(Path)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Upstream_serviceDesc = grpc.ServiceDesc{
	ServiceName: "remote.Upstream",
	HandlerType: (*UpstreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Upload",
			Handler:       _Upstream_Upload_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Remove",
			Handler:       _Upstream_Remove_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "remote.proto",
}
