name: Test UI

on:
  pull_request:
    branches:
      - main
    paths:
      - "ui/**"
      - "hack/build-ui.bash"
      - ".github/workflows/ui.yaml"

jobs:
  test-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: ui/.nvmrc
          cache: npm
          cache-dependency-path: ui/package-lock.json
      - name: Build UI
        env:
          CI: "false"
        run: ./hack/build-ui.bash
